version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=romansulymka
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U romansulymka" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    image: romansulymka/latest:tagname
    restart: always
    environment:
      - DB_HOST=postgres
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy