version: '3.3'
services:
  postgres_mywallet:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: mywallet
      POSTGRES_USER: romansulymka
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'

  postgres_analytics:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: romansulymka
      POSTGRES_PASSWORD: admin

  zookeeper1:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

  zookeeper2:
    image: wurstmeister/zookeeper
    ports:
      - "2182:2181"
    restart: unless-stopped

  zookeeper3:
    image: wurstmeister/zookeeper
    ports:
      - "2183:2181"
    restart: unless-stopped

  kafka1:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181, zookeeper2:2181, zookeeper3:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_AUTO_OFFSET_RESET: earliest
      ALLOW_PLAINTEXT_LISTENER: "yes"
    restart: unless-stopped

  kafka2:
    image: bitnami/kafka
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181, zookeeper2:2181, zookeeper3:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_AUTO_OFFSET_RESET: earliest
      ALLOW_PLAINTEXT_LISTENER: "yes"
    restart: unless-stopped

  kafka3:
    image: bitnami/kafka
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181, zookeeper2:2181, zookeeper3:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_AUTO_OFFSET_RESET: earliest
      ALLOW_PLAINTEXT_LISTENER: "yes"
    restart: unless-stopped

  quick-analytics1:
    build:
      context: .
    image: romansulymka/quick-analytics:tagname
    restart: always
    environment:
      - POSTGRES_HOST=postgres_analytics
      - POSTGRES_DB=analytics
      - spring.kafka.bootstrap-servers=kafka1:9092,kafka2:9092,kafka3:9092
      - spring.kafka.consumer.group-id=quick-analytics-group
      - spring.kafka.consumer.auto-offset.reset=earliest
    ports:
      - '6060:6060'
    depends_on:
      - postgres_analytics
      - kafka1

  quick-analytics2:
    build:
      context: .
    image: romansulymka/quick-analytics:tagname
    restart: always
    environment:
      - POSTGRES_HOST=postgres_analytics
      - POSTGRES_DB=analytics
      - spring.kafka.bootstrap-servers=kafka1:9092,kafka2:9092,kafka3:9092
      - spring.kafka.consumer.group-id=quick-analytics-group
      - spring.kafka.consumer.auto-offset.reset=earliest
    ports:
      - '6061:6060'
    depends_on:
      - postgres_analytics
      - kafka1

  quick-analytics3:
    build:
      context: .
    image: romansulymka/quick-analytics:tagname
    restart: always
    environment:
      - POSTGRES_HOST=postgres_analytics
      - POSTGRES_DB=analytics
      - spring.kafka.bootstrap-servers=kafka1:9092,kafka2:9092,kafka3:9092
      - spring.kafka.consumer.group-id=quick-analytics-group
      - spring.kafka.consumer.auto-offset.reset=earliest

    ports:
      - '6062:6060'
    depends_on:
      - postgres_analytics
      - kafka1

  app:
    build:
      context: .
    image: romansulymka/latest:tagname
    environment:
      - POSTGRES_HOST=postgres_mywallet
      - POSTGRES_DB=mywallet
      - JWT_SECRET_KEY=7134743777397A24432646294A404E635266556A586E3272357538782F412544
      - spring.kafka.bootstrap-servers=kafka1:9092,kafka2:9092,kafka3:9092
    ports:
      - '8080:8080'
    depends_on:
      - postgres_mywallet
      - kafka1
